/* Generated by Yosys 0.67+24 (git sha1 0e82bbefe, Release, Clang /usr/bin/clang++ 18.1.8) */

module register_gate(clock, next, reset, value, write_enable);
  input clock;
  wire clock;
  input [31:0] next;
  wire [31:0] next;
  input reset;
  wire reset;
  output [31:0] value;
  wire [31:0] value;
  input write_enable;
  wire write_enable;
  \$_SDFFE_PP0P_  \value_reg[0]  /* _00_ */ (
    .C(clock),
    .D(next[0]),
    .E(write_enable),
    .Q(value[0]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[1]  /* _01_ */ (
    .C(clock),
    .D(next[1]),
    .E(write_enable),
    .Q(value[1]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[2]  /* _02_ */ (
    .C(clock),
    .D(next[2]),
    .E(write_enable),
    .Q(value[2]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[3]  /* _03_ */ (
    .C(clock),
    .D(next[3]),
    .E(write_enable),
    .Q(value[3]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[4]  /* _04_ */ (
    .C(clock),
    .D(next[4]),
    .E(write_enable),
    .Q(value[4]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[5]  /* _05_ */ (
    .C(clock),
    .D(next[5]),
    .E(write_enable),
    .Q(value[5]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[6]  /* _06_ */ (
    .C(clock),
    .D(next[6]),
    .E(write_enable),
    .Q(value[6]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[7]  /* _07_ */ (
    .C(clock),
    .D(next[7]),
    .E(write_enable),
    .Q(value[7]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[8]  /* _08_ */ (
    .C(clock),
    .D(next[8]),
    .E(write_enable),
    .Q(value[8]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[9]  /* _09_ */ (
    .C(clock),
    .D(next[9]),
    .E(write_enable),
    .Q(value[9]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[10]  /* _10_ */ (
    .C(clock),
    .D(next[10]),
    .E(write_enable),
    .Q(value[10]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[11]  /* _11_ */ (
    .C(clock),
    .D(next[11]),
    .E(write_enable),
    .Q(value[11]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[12]  /* _12_ */ (
    .C(clock),
    .D(next[12]),
    .E(write_enable),
    .Q(value[12]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[13]  /* _13_ */ (
    .C(clock),
    .D(next[13]),
    .E(write_enable),
    .Q(value[13]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[14]  /* _14_ */ (
    .C(clock),
    .D(next[14]),
    .E(write_enable),
    .Q(value[14]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[15]  /* _15_ */ (
    .C(clock),
    .D(next[15]),
    .E(write_enable),
    .Q(value[15]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[16]  /* _16_ */ (
    .C(clock),
    .D(next[16]),
    .E(write_enable),
    .Q(value[16]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[17]  /* _17_ */ (
    .C(clock),
    .D(next[17]),
    .E(write_enable),
    .Q(value[17]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[18]  /* _18_ */ (
    .C(clock),
    .D(next[18]),
    .E(write_enable),
    .Q(value[18]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[19]  /* _19_ */ (
    .C(clock),
    .D(next[19]),
    .E(write_enable),
    .Q(value[19]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[20]  /* _20_ */ (
    .C(clock),
    .D(next[20]),
    .E(write_enable),
    .Q(value[20]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[21]  /* _21_ */ (
    .C(clock),
    .D(next[21]),
    .E(write_enable),
    .Q(value[21]),
    .R(reset)
  );
  \$_SDFFE_PP1P_  \value_reg[22]  /* _22_ */ (
    .C(clock),
    .D(next[22]),
    .E(write_enable),
    .Q(value[22]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[23]  /* _23_ */ (
    .C(clock),
    .D(next[23]),
    .E(write_enable),
    .Q(value[23]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[24]  /* _24_ */ (
    .C(clock),
    .D(next[24]),
    .E(write_enable),
    .Q(value[24]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[25]  /* _25_ */ (
    .C(clock),
    .D(next[25]),
    .E(write_enable),
    .Q(value[25]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[26]  /* _26_ */ (
    .C(clock),
    .D(next[26]),
    .E(write_enable),
    .Q(value[26]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[27]  /* _27_ */ (
    .C(clock),
    .D(next[27]),
    .E(write_enable),
    .Q(value[27]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[28]  /* _28_ */ (
    .C(clock),
    .D(next[28]),
    .E(write_enable),
    .Q(value[28]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[29]  /* _29_ */ (
    .C(clock),
    .D(next[29]),
    .E(write_enable),
    .Q(value[29]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[30]  /* _30_ */ (
    .C(clock),
    .D(next[30]),
    .E(write_enable),
    .Q(value[30]),
    .R(reset)
  );
  \$_SDFFE_PP0P_  \value_reg[31]  /* _31_ */ (
    .C(clock),
    .D(next[31]),
    .E(write_enable),
    .Q(value[31]),
    .R(reset)
  );
endmodule

module register_gold(clock, next, reset, value, write_enable);
  input clock;
  wire clock;
  input [31:0] next;
  wire [31:0] next;
  input reset;
  wire reset;
  output [31:0] value;
  wire [31:0] value;
  input write_enable;
  wire write_enable;
  \$_DFFE_PP0P_  \value_reg[0]  /* _00_ */ (
    .C(clock),
    .D(next[0]),
    .E(write_enable),
    .Q(value[0]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[1]  /* _01_ */ (
    .C(clock),
    .D(next[1]),
    .E(write_enable),
    .Q(value[1]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[2]  /* _02_ */ (
    .C(clock),
    .D(next[2]),
    .E(write_enable),
    .Q(value[2]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[3]  /* _03_ */ (
    .C(clock),
    .D(next[3]),
    .E(write_enable),
    .Q(value[3]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[4]  /* _04_ */ (
    .C(clock),
    .D(next[4]),
    .E(write_enable),
    .Q(value[4]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[5]  /* _05_ */ (
    .C(clock),
    .D(next[5]),
    .E(write_enable),
    .Q(value[5]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[6]  /* _06_ */ (
    .C(clock),
    .D(next[6]),
    .E(write_enable),
    .Q(value[6]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[7]  /* _07_ */ (
    .C(clock),
    .D(next[7]),
    .E(write_enable),
    .Q(value[7]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[8]  /* _08_ */ (
    .C(clock),
    .D(next[8]),
    .E(write_enable),
    .Q(value[8]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[9]  /* _09_ */ (
    .C(clock),
    .D(next[9]),
    .E(write_enable),
    .Q(value[9]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[10]  /* _10_ */ (
    .C(clock),
    .D(next[10]),
    .E(write_enable),
    .Q(value[10]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[11]  /* _11_ */ (
    .C(clock),
    .D(next[11]),
    .E(write_enable),
    .Q(value[11]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[12]  /* _12_ */ (
    .C(clock),
    .D(next[12]),
    .E(write_enable),
    .Q(value[12]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[13]  /* _13_ */ (
    .C(clock),
    .D(next[13]),
    .E(write_enable),
    .Q(value[13]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[14]  /* _14_ */ (
    .C(clock),
    .D(next[14]),
    .E(write_enable),
    .Q(value[14]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[15]  /* _15_ */ (
    .C(clock),
    .D(next[15]),
    .E(write_enable),
    .Q(value[15]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[16]  /* _16_ */ (
    .C(clock),
    .D(next[16]),
    .E(write_enable),
    .Q(value[16]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[17]  /* _17_ */ (
    .C(clock),
    .D(next[17]),
    .E(write_enable),
    .Q(value[17]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[18]  /* _18_ */ (
    .C(clock),
    .D(next[18]),
    .E(write_enable),
    .Q(value[18]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[19]  /* _19_ */ (
    .C(clock),
    .D(next[19]),
    .E(write_enable),
    .Q(value[19]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[20]  /* _20_ */ (
    .C(clock),
    .D(next[20]),
    .E(write_enable),
    .Q(value[20]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[21]  /* _21_ */ (
    .C(clock),
    .D(next[21]),
    .E(write_enable),
    .Q(value[21]),
    .R(reset)
  );
  \$_DFFE_PP1P_  \value_reg[22]  /* _22_ */ (
    .C(clock),
    .D(next[22]),
    .E(write_enable),
    .Q(value[22]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[23]  /* _23_ */ (
    .C(clock),
    .D(next[23]),
    .E(write_enable),
    .Q(value[23]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[24]  /* _24_ */ (
    .C(clock),
    .D(next[24]),
    .E(write_enable),
    .Q(value[24]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[25]  /* _25_ */ (
    .C(clock),
    .D(next[25]),
    .E(write_enable),
    .Q(value[25]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[26]  /* _26_ */ (
    .C(clock),
    .D(next[26]),
    .E(write_enable),
    .Q(value[26]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[27]  /* _27_ */ (
    .C(clock),
    .D(next[27]),
    .E(write_enable),
    .Q(value[27]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[28]  /* _28_ */ (
    .C(clock),
    .D(next[28]),
    .E(write_enable),
    .Q(value[28]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[29]  /* _29_ */ (
    .C(clock),
    .D(next[29]),
    .E(write_enable),
    .Q(value[29]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[30]  /* _30_ */ (
    .C(clock),
    .D(next[30]),
    .E(write_enable),
    .Q(value[30]),
    .R(reset)
  );
  \$_DFFE_PP0P_  \value_reg[31]  /* _31_ */ (
    .C(clock),
    .D(next[31]),
    .E(write_enable),
    .Q(value[31]),
    .R(reset)
  );
endmodule
